### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [anhpnguyen/meal-planner#2]
:+1: Looks good. I'll open up a pull request to help you with the tabs after I review the rest of the assignments for this week.

**Comment by anhpnguyen** [comment]
Thanks! I have a question. When you accept a pull request, how do you
update the project directory on your computer?

**Comment by chrisvfritz** [comment]
That's a great question. You have a couple options, but the easiest would probably be to run `git pull origin` from the command line, in your project folder.
